# We can't remove volumes in a compose override, for the test configuration using the final containers
# we don't want the volumes so this is the default override file to add the volumes in the dev case
# any override will need to include these volumes to use them.
# see:  https://github.com/docker/compose/issues/3729
---
version: "3.8"
services:
  nautobot:
    volumes:
      - "media_nautobot:/opt/nautobot/media"
      - "${PWD}/development/nautobot_config.py:/opt/nautobot/nautobot_config.py"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  docs:
    depends_on:
      nautobot:
          condition: "service_healthy"
  worker:
    volumes:
      - "media_nautobot:/opt/nautobot/media"
      - "${PWD}/development/nautobot_config.py:/opt/nautobot/nautobot_config.py"
    depends_on:
      nautobot:
          condition: "service_healthy"

  beat:
    volumes:
      - "media_nautobot:/opt/nautobot/media"
      - "${PWD}/development/nautobot_config.py:/opt/nautobot/nautobot_config.py"
    depends_on:
      nautobot:
          condition: "service_healthy"
      worker:
          condition: "service_healthy"

  db:
    # ports:
    #   - "5432:5432"
    volumes:
      - "pgdata_nautobot:/var/lib/postgresql/data"


# redis:
#   ports:
#     - "6379:6379"
volumes:
  pgdata_nautobot:
  media_nautobot:
